### ISSUE TITLE
Acacia Plank Trophy Not Given

### ISSUE THREAD

**Issue by MokahTGS** [davqvist/CustomAchievements#5]
In the example file, you have a trophy to be given when the player finished the Acacia Plank Achievement.  I did the Achievement got it in the UI but did not receive a trophy.  Is there something I'm missing?

From the json:

    {
      "uid": "craftAcaciaPlanks",
      "name": "Acacia Planks crafted",
      "desc": "Craft Acacia Planks",
      "type": "Craft",
      "item": "minecraft:planks",
      "meta": 4,
      "ignoreMeta": false,
      "parent": "detectLog",
      "trophy": true,
      "xpos": 1,
      "ypos": 0
    }

**Comment by davqvist** [comment]
Can you post more info? Which MC version? Forge version? CA version?
Have you installed additional mods like Better Achievements?
Have you gotten the required achievement before it (picking up a log)?

**Comment by MokahTGS** [comment]
MC 1.10.2
Forge 12.18.3.2281
Better Achievements 1.10.2.0.3.3.10
Custom Achievements 1.10.2-0.2.5

Yes, all prereq Achievements done.  The achieves happened, just not receiving the trophy.

**Comment by davqvist** [comment]
So I assume you crafted Acacia Planks before you had picked up a log so you hadn't the prerequisites. Then you picked up a log and then Better Achievements gave you the achievement retroactively which is what the mod does. When it does that, you don't get the trophy though. You have to get rid of BetterAchievements or make sure that you trigger the achievements in order, Let me know if this is the case.

**Comment by MokahTGS** [comment]
Is there any way to reload the achievements so I can test things?

**Comment by davqvist** [comment]
Not sure what you mean with reload? You can test in another world or you can type /achievement take achievement.uuid yourname to remove an achievement (uuid is the name of the achievement and yourname your IGN)

**Comment by MokahTGS** [comment]
Yes, that will do.  But there are other json mods that allow for editing the .json while in game and the typing /reload will have the game read the changes.  It makes for a much easier map and modpack building experience.  The mod Custom Lore does this.

**Comment by davqvist** [comment]
Not sure if I can change achievements on the fly. I will have a look in the future.
Let me know if getting the trophy worked for you, so that I can close this issue.

**Comment by davqvist** [comment]
I take that as yes.

**Comment by MokahTGS** [comment]
Sorry im out of town for multiple weeks.   I'll look at this later.
