### ISSUE TITLE
Trophy not given 1.11 in some cases

### ISSUE THREAD

**Issue by Mattabase** [davqvist/CustomAchievements#7]
When I use OP commands to give a user an achievement it does not give them the trophy.

**Comment by davqvist** [comment]
Yes I know that, not sure if there is a way around that. Let me try to figure this out.

**Comment by Mattabase** [comment]
Thanks. 

Yeah, I was hoping to use Better Questing to give some of the Achievements for some tracking stuff I am doing in BQ. Would just be a bummer to not have trophies.

**Comment by davqvist** [comment]
Fixed in 0.3.3
